function flc = createFLC_custom()
% Build Mamdani FLC structure with membership functions, rules, etc.

% Input ranges
flc.inputs(1).name = 'Temperature';
flc.inputs(1).range = [15 35];
flc.inputs(1).mf = {...
    struct('name','Cold',       'type','trapmf', 'params',[15 15 19 21]), ...
    struct('name','Cool',       'type','trimf',  'params',[17 21 25]), ...
    struct('name','Comfortable','type','trimf',  'params',[21 24 27]), ...
    struct('name','Warm',       'type','trimf',  'params',[24 28 32]), ...
    struct('name','Hot',        'type','trapmf', 'params',[28 32 35 35]) };

flc.inputs(2).name = 'Light';
flc.inputs(2).range = [0 1000];
flc.inputs(2).mf = {...
    struct('name','Dark',       'type','trapmf', 'params',[0 0 50 150]), ...
    struct('name','Dim',        'type','trimf',  'params',[50 200 350]), ...
    struct('name','Moderate',   'type','trimf',  'params',[200 400 600]), ...
    struct('name','Bright',     'type','trimf',  'params',[450 700 850]), ...
    struct('name','Very_Bright','type','trapmf', 'params',[750 1000 1000 1000]) };

% Output ranges
flc.outputs(1).name = 'HeaterCooler';
flc.outputs(1).range = [0 100];
flc.outputs(1).mf = {...
    struct('name','Cool_Max', 'type','trapmf', 'params',[0 0 10 25]), ...
    struct('name','Cool_Low', 'type','trimf',  'params',[10 25 45]), ...
    struct('name','Off',      'type','trimf',  'params',[30 50 70]), ...
    struct('name','Heat_Low', 'type','trimf',  'params',[55 75 90]), ...
    struct('name','Heat_Max', 'type','trapmf', 'params',[75 100 100 100]) };

flc.outputs(2).name = 'Dimmer';
flc.outputs(2).range = [0 100];
flc.outputs(2).mf = {...
    struct('name','Off',    'type','trapmf', 'params',[0 0 5 15]), ...
    struct('name','Low',    'type','trimf',  'params',[5 25 45]), ...
    struct('name','Medium', 'type','trimf',  'params',[35 55 75]), ...
    struct('name','High',   'type','trimf',  'params',[65 85 100]), ...
    struct('name','Full',   'type','trapmf', 'params',[90 100 100 100]) };

% Rules: each rule = [in1_mf_idx, in2_mf_idx, out1_mf_idx, out2_mf_idx, weight]
% Use -1 for "don't care" (i.e., no condition on that input)
rules = [
    1, -1, 5, -1, 1;   % If Temp Cold -> Heat_Max
    2, -1, 4, -1, 1;   % Cool -> Heat_Low
    3, -1, 3, -1, 1;   % Comfortable -> Off
    4, -1, 2, -1, 1;   % Warm -> Cool_Low
    5, -1, 1, -1, 1;   % Hot -> Cool_Max
    -1, 5, -1, 1, 1;   % Very_Bright -> Dimmer Off
    -1, 4, -1, 3, 1;   % Bright -> Medium
    -1, 3, -1, 2, 1;   % Moderate -> Low
    -1, 2, -1, 4, 1;   % Dim -> High
    -1, 1, -1, 5, 1;   % Dark -> Full
    3, 3, 3, 2, 1;     % Comfortable & Moderate -> Off & Low
    ];
flc.rules = rules;

% Inference settings
flc.andMethod = @min;
flc.orMethod  = @max;
flc.impMethod = @min;      % implication (Mamdani)
flc.aggMethod = @max;      % aggregation
flc.defuzzMethod = 'centroid';
end